version: 2
jobs:
  build:
    docker:
      - image: integratedexperts/circleci2-builder
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer validate --strict
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: composer cs
    branch: 8.x-1.x
    commands:
      - git fetch --unshallow
      - git remote add drupalorg alex.designworks@git.drupal.org:project/drupal_helpers.git

  publish:
    docker:
      - image: integratedexperts/circleci2-builder
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2d:71:4d:aa:4d:34:38:b5:8f:af:ca:3b:d4:82:6a:21"
      - run:
          name: Configure git
          command: |
            git config --global user.email "$DEPLOY_USER_EMAIL" && git config --global user.name "$DEPLOY_USER_NAME"
            mkdir -p ~/.ssh/ && echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            DEPLOY_SSH_FINGERPRINT="2d:71:4d:aa:4d:34:38:b5:8f:af:ca:3b:d4:82:6a:21" && DEPLOY_SSH_FILE="${DEPLOY_SSH_FINGERPRINT//:}" && DEPLOY_SSH_FILE="id_rsa_${DEPLOY_SSH_FILE//\"}" && ssh-add -D && ssh-add ~/.ssh/$DEPLOY_SSH_FILE
      - run: git remote add drupalorg alex.designworks@git.drupal.org:project/jsonapi_embed.git
      - run: git push --tags drupalorg $CIRCLE_BRANCH

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: 8.x-1.x
